source "https://github.com/CocoaPods/Specs.git"

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Oishii' do

 # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Oishii
  pod 'Firebase/Core'

  target 'OishiiTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OishiiUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
